-- CreateTable
CREATE TABLE "LINES" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "LINES_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "STATION_LINE" (
    "id" SERIAL NOT NULL,
    "station_id" INTEGER NOT NULL,
    "line_id" INTEGER NOT NULL,

    CONSTRAINT "STATION_LINE_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "STATION_LINE" ADD CONSTRAINT "STATION_LINE_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "STATIONS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "STATION_LINE" ADD CONSTRAINT "STATION_LINE_line_id_fkey" FOREIGN KEY ("line_id") REFERENCES "LINES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
